### ISSUE TITLE
Epoch._check_values() doesn't allow 59.917815 seconds

### ISSUE THREAD

**Issue by molsen234** [architest/pymeeus#1]
Epoch._check_values() throws an exception when offered datetime values where the seconds are above 59.0 and below 60.0 seconds.

In my opinion the following check (line 433-434 in Epoch.py):

        if sec < 0 or sec > 59:
            raise ValueError("Invalid value for the input seconds")

Should instead be:

        if sec < 0 or sec >= 60:
            raise ValueError("Invalid value for the input seconds")

I fully understand that a fraction of a second is likely to matter very little in the accuracy of the functions depending on the epoch. However, when running through a loop while incrementing a datetime, fractional seconds are useful to avoid error build-up. For example, an iteration over tropical days:
```
    # Approximate tropical day
    tdelta = datetime.timedelta(days=365, hours=5, minutes=48,seconds=46)/365
    maxd = 366
    for y in range(0,maxd):
        mydate = datetime.datetime(2019, 6, 21, 12, 0, 0,tzinfo=datetime.timezone.utc)+tdelta*d
        myepoch = pymeeus.Epoch.Epoch(mydate)
        # Do stuff with Epoch here
```

Here I run into a datetime of 2019-08-05 12:42:59.917815+00:00 which to me seems like a valid datetime. Yet it of course throws an exception:

```
  File "c:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\site-packages\pymeeus\Epoch.py", line 199, in __init__
    self.set(*args, **kwargs)  # Use 'set()' method to handle the setup
  File "c:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\site-packages\pymeeus\Epoch.py", line 312, in set
    d.second + d.microsecond / 1e6,
  File "c:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\site-packages\pymeeus\Epoch.py", line 434, in _check_values
    raise ValueError("Invalid value for the input seconds")
ValueError: Invalid value for the input seconds
Error: Python script failed, check the message in the system console
```

I may be wrong on this, if so it would be great if you could let me know why :)

That aside, thank you very much for making this wonderful library available! Apart from the above, it works perfectly for my needs, and has saved me a ton of time.

**Comment by architest** [comment]
Dear molsen234,

Thank you very much for your message. It makes me happy that people find
useful the software that I've written. :-)

You were indeed right that the Epoch class had a bug in the _check_values()
method. After looking at it carefully, I came to the conclusion that the
problem was not only limited to the seconds, but it also applied to
minutes, hours and days: the and of the range should be allowed to have
decimal values, for the sake of completeness.

I've already fixed the situation and, plus a minor improvement in the
documentation, I uploaded the changes to PyPI as version 0.3.7.

Best regards,

Dagoberto Salazar

**Comment by molsen234** [comment]
Hello Dagoberto,

Thank you very much for the fast feedback!

I was wondering about the fractional hours and minutes, but did not want to report those as a bug, since the checks did not prevent specifying a valid datetime. In my scenario I have no need for 23.5 hours as a timestamp for example.

Again thanks for the bugfix! I've updated to your latest version and it works perfectly :)

If you are curious, I am using your library to create 3D animations in Blender via the built-in python scripting language. Since you do not (yet?) have a Moon object, I took those calculations from AstroPy instead, but that uses numpy and a pretty complete VSOP97, so there is a large overhead for the precision I need.

If I decide to implement a version from the Meeus book instead, would you be interested in having the code?

Feel free to close this bug report, I am fully satisfied with the solution you implemented.

Many kind regards,
Michael

**Comment by architest** [comment]
Hi Michael!

If you are curious, I am using your library to create 3D animations in
> Blender via the built-in python scripting language. Since you do not (yet?)
> have a Moon object, I took those calculations from AstroPy instead, but
> that uses numpy and a pretty complete VSOP97, so there is a large overhead
> for the precision I need.
>

Your project sounds very interesting. I wish you a lot of success!.

Regarding the Moon object, I intend to add that class next month, if all
things go as expected.

Cheers,

Dago



>
