### ISSUE TITLE
Test on more python versions

### ISSUE THREAD

**Issue by sevdog** [architest/pymeeus#15]
As of now this libs tests only on two versions of Python (2.7, which is EOL, and 3.6):

https://github.com/architest/pymeeus/blob/6e45b16e685b268548bebc2ea08e0ab29741fad3/.circleci/config.yml#L76-L79

It should be also tested on more recent versions of Python (from 3.7 to 3.9 at least). Also it would be a good approach to drop support for Python 2.7 which is no more supported by PSF.

**Comment by hugovk** [comment]
Please see PR #16 to drop support for EOL Python 2.7.

**Comment by architest** [comment]
Dear sevdog and hugovk,

Thank you very much for your suggestions and sorry for a (very) long time to answer this issue, but I've thought about it long and hard.

First, let's indicate that currently PyMeeus is tested in four different Python versions:

- 2.7
- 3.6.7
- 3.7.12
- 3.9.5

It passes the tests flawlessly in all those versions.

Second, I've decided that I'm NOT going to drop the support for version 2.7. The reasons are the following:

- In astronomy, the code base changes very slowly. The emphasis is on reliability, not on bleeding-edge features. Indeed, much of the astronomy software is written in Fortran77
(heck! my thesis advisors still use Fortran77!). Therefore, is quite probable that some systems being used for astronomy have an old Python version installed.

- Dropping support for version 2.7 adds absolutely nothing to PyMeeus, on the contrary, it subtracts advantages: Backwards compatibility is reduced and people not familiar with
the latest Python versions will have extra trouble reading the code, among other things.

Therefore, I'll keep version 2.7 for the foreseeable future, until a change in Python definitively breaks the backward compatibility and in the meantime, I'll add additional tests to the CircleCI configuration as new Python versions are released.

Best regards,

Dago

**Comment by sevdog** [comment]
@architest I understand your desire to keep a long (maybe very long?) term support for older python version.

Is it possible to at least add some tests for newer versions of python which may introduce a breaking change since the setup file in this project does not declare the [`python_requires`](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires) and thus package manager software considers it valid for _every_ python version?

**Comment by hugovk** [comment]
Here's the `python_requires` for 2.7 and 3.6+:

`python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*', !=3.5.*',`

It might make sense to test the newest released version (3.11) because things are routinely deprecated and removed from Python.

**Comment by architest** [comment]
I just modified the CircleCi tests to include Python versions:

- 2.7
- 3.7
- 3.9
- 3.10
- 3.11

Version 0.5.12 of PyMeeus was just released, including a bugfix in the winter solstice computation.
