### ISSUE TITLE
error in winter solstice

### ISSUE THREAD

**Issue by zivoslav** [architest/pymeeus#17]
```python

for year in range(-1000, 2100):
   
    for season in ["spring", "summer", "autumn", "winter"]:
        day = Sun.get_equinox_solstice(year, target=season)
        y, m, d, h, mi, s  = day.get_full_date()
        print("{} {} {} {} {} {}:{}:{}".format(year, season, y, m, d, h, mi, round(s, 0)))
```

Winter year is of 5 year moved:

-986 winter -981 12 30 15:8:59.0
-985 spring -985 3 31 8:3:16.0
-985 summer -985 7 3 14:5:52.0
-985 autumn -985 10 3 5:32:45.0
-985 winter -980 12 29 21:4:25.0
-984 spring -984 3 30 13:56:48.0
-984 summer -984 7 2 20:3:54.0
-984 autumn -984 10 2 11:24:45.0
-984 winter -979 12 30 3:0:45.0
-983 spring -983 3 30 19:47:56.0
-983 summer -983 7 3 1:52:5.0
-983 autumn -983 10 2 17:15:57.0
-983 winter -978 12 30 8:47:47.0
-982 spring -982 3 31 1:35:33.0
-982 summer -982 7 3 7:36:26.0
-982 autumn -982 10 2 23:10:44.0
-982 winter -977 12 30 14:38:39.0
-981 spring -981 3 31 7:28:26.0
-981 summer -981 7 3 13:26:37.0
-981 autumn -981 10 3 5:1:53.0
-981 winter -976 12 29 20:26:12

**Comment by architest** [comment]
Dear zivoslav,

This looks indeed like a bug, but currently I'm not sure where it comes from. I'll look further into it and I'll release a new fixed version as soon as possible.

**Comment by architest** [comment]
Dear @zivoslav

I found the bug in the winter solstice computation. It was a wrong decimal when taken from Table 27.A, page 178. Version 0.5.12 of PyMeeus was just released, including this bugfix. Thanks.
