### ISSUE TITLE
How to cite PyMeeus?

### ISSUE THREAD

**Issue by benoitespinola** [architest/pymeeus#21]
Greetings,

For those who publish results using your library.

How would you like citations for the PyMeeus library to be?

Would it be possible to add a citation suggestion in the documentation?

Do you have a publication on this library one could cite?

I am not sure this is the right channel, apologies if this was not appropriate.

Thank you in advance,

Best regards,

Benoit

**Comment by architest** [comment]
Dear Benoit,

Honestly, I haven't thought about it, and I haven't yet published about
PyMeeus.

Looking around I found that this cite is adequate:

Salazar, D (2022 <2022>) PyMeeus: Library of astronomical algorithms in
Python (Version 0.5.12 <0512>) [Source code].
https://github.com/architest/pymeeus

The source for this format is the following:

https://guides.libraries.uc.edu/citing/code

I hope it fulfills your requirements.

Best regards,

Dago

**Comment by benoitespinola** [comment]
That is great, thank you for the library. It has been really helpful.
