### ISSUE TITLE
Interpolation in Coordinates.times_rise_transit_set() fails when values wrap around 360

### ISSUE THREAD

**Issue by janbredenbeek** [architest/pymeeus#23]
As mentioned in Meeus's book, when interpolating values such as Right Ascension and longitudes, care must be taken when they wrap from 360 degrees (or 24h) to zero (e.g. an increase from 359 to 1 degrees should be interpolated as 361, not 1). However, testing and possibly adjusting the input of `Coordinates.times_rise_transit_set()` still yields wrong interpolation results. This is caused by the `interpol()` function not converting the Angle() objects y1, y2 and y3 to float before interpolating, hence the values get reduced to range 0..360.

The fix is to convert y1, y2 and y3 to float before interpolating and reducing the differences to -180..+180:

    def interpol(n, y1, y2, y3):
        a = y2() - y1() # convert to float so avoid reducing to 0..360
        a = a - 360.0 * round(a / 360.0) # reduce to -180..+180
        b = y3() - y2()
        b = b - 360.0 * round(b / 360.0)
        c = b - a
        return y2 + n * (a + b + n * c) / 2.0

(Note that this requires the arguments of `interpol()` to be Angle() objects, but the function is local to this method and all calls within this method use Angle() objects).

**Comment by architest** [comment]
Dear janbredenbeek,

I've applied the modifications you suggested. Thank you very much! I'll work fixing the other pending issues and I'll release a new version.

Sorry for the delay: I've been very sick and I'm just recovering.

**Comment by janbredenbeek** [comment]
Thanks, hope you'll have a speedy recovery.
