### ISSUE TITLE
Missing README.rst in the package

### ISSUE THREAD

**Issue by harsha-mohan** [architest/pymeeus#4]
It looks like it is missing README.rst in the latest package (1 hour ago). I would kindly ask you to fix this as this is a dependency for this package - holidays==0.10.5.2

```
pip install pymeeus

Collecting pymeeus
  Using cached https://files.pythonhosted.org/packages/6e/e1/dccf1d8f8dabb234f0602ab57fc383ce6ba97a6f64f6757a9e5a7e10b7ad/PyMeeus-0.3.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-y0k_daqp/pymeeus/setup.py", line 12, in <module>
        with open(path.join(here, 'README.rst')) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-y0k_daqp/pymeeus/README.rst'
```

**Comment by harsha-mohan** [comment]
For interested people - version 0.3.7 works. Thankfully I did a pip freeze last night, so I know what worked. 🙃

**Comment by architest** [comment]
Dear Harsha,

I just updated a new version (0,3,9) which hopefully has the proper README
files.

Best regards,

Dagoberto

**Comment by harsha-mohan** [comment]
I just checked my workspace and version 0.3.9 works well with the holiday's python package.`[https://pypi.org/project/holidays/]` Thank you! 🙌  @architest
