### ISSUE TITLE
UnicodeDecodeError while installing

### ISSUE THREAD

**Issue by ajaykumarbharaj** [architest/pymeeus#5]
Collecting pymeeus==0.3.9
  Using cached PyMeeus-0.3.9.tar.gz (5.3 MB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\unknown\\AppData\\Local\\Temp\\17\\pi
p-install-lllhqdzk\\pymeeus_7fd3c7ad574947d7b68f8c40e8d493fc\\setup.py'"'"'; __file__='"'"'C:\\Users\\unknown\\AppData\\Local\\Temp\\17\\pip-install-
lllhqdzk\\pymeeus_7fd3c7ad574947d7b68f8c40e8d493fc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'
"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\unknown\AppData\Local\Temp\17\pip-pip-egg-
info-44kowm40'
         cwd: C:\Users\unknown\AppData\Local\Temp\17\pip-install-lllhqdzk\pymeeus_7fd3c7ad574947d7b68f8c40e8d493fc\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\unknown\AppData\Local\Temp\17\pip-install-lllhqdzk\pymeeus_7fd3c7ad574947d7b68f8c40e8d493fc\setup.py", line 13, in <module>
        long_description = f.read()
      File "D:\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 237: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by architest** [comment]
Pull request accepted. Issue closed.

**Comment by salimfadhleyhtp** [comment]
This issue is still affecting the version on PyPi:
```
Collecting pymeeus==0.3.9
  Downloading PyMeeus-0.3.9.tar.gz (5.3 MB)
     |████████████████████████████████| 5.3 MB 6.8 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\installs\anaconda\envs\eunrg_weather_control\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\SFadhley\\AppData\\Local\\Temp\\pip-install-7ejryqtb\\pymeeus_976b7a80bc4241cb91983957d19
51ab0\\setup.py'"'"'; __file__='"'"'C:\\Users\\SFadhley\\AppData\\Local\\Temp\\pip-install-7ejryqtb\\pymeeus_976b7a80bc4241cb91983957d1951ab0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('
"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\SFadhley\AppData\Local\Temp\pip-pip-egg-info-efw507s9'
         cwd: C:\Users\SFadhley\AppData\Local\Temp\pip-install-7ejryqtb\pymeeus_976b7a80bc4241cb91983957d1951ab0\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SFadhley\AppData\Local\Temp\pip-install-7ejryqtb\pymeeus_976b7a80bc4241cb91983957d1951ab0\setup.py", line 13, in <module>
        long_description = f.read()
      File "C:\installs\anaconda\envs\eunrg_weather_control\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 237: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ajaykumarbharaj** [comment]
some how changes not updated to pypi

**QUICK FIX**
pip install git+https://github.com/architest/pymeeus
